In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [4]:
df=pd.read_csv('homeprices.csv')

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
df.bedrooms.fillna(df.bedrooms.median(),inplace=True)

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
x_df=df.drop("price",axis=1)
y_df=df.price

In [11]:
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [13]:
lr.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
lr.intercept_

221323.00186540408

In [23]:
#y=  112.06244194*area + 23388.88007794*bedrooms-3231.71790863*age

In [20]:
lr.predict([[3000,3,15]])

array([579201.19929613])

In [21]:
lr.predict([[3000,3,40]])

array([498408.25158031])

In [22]:
df.corr()['price'].sort_values(ascending=False)

price       1.000000
bedrooms    0.919803
area        0.901476
age        -0.734167
Name: price, dtype: float64

In [ ]:
#here bedroom is more corelated to price 91 %+
#area 90% o
#age = the older the house ,price will decrease,#depreciation

In [ ]:
y=  112.06244194*area + 23388.88007794*bedrooms-3231.71790863*age
#y= m1X1+m2X2+m3X3+B
m1 ,m2,m3 are coefficients of the

In [26]:
lr.predict([[2500,4,5]])

array([578876.03748933])

In [ ]:
# lr.fit